# Copyright (c) 2020 NVIDIA Corporation.  All rights reserved. 

# To build the singularity container, run: $  singularity build --fakeroot nways_c.simg nways_Singularity
# To copy the content of the container: $ singularity run nways_c.simg cp -rT /labs ~/labs
# To run: $ singularity run --nv nways_c.simg jupyter-lab --notebook-dir=~/labs
# Finally, open http://localhost:8888/

Bootstrap: docker
FROM: nvcr.io/nvidia/nvhpc:24.1-devel-cuda_multi-ubuntu22.04

%environment
    export XDG_RUNTIME_DIR=
    export PATH="/usr/local/bin:/opt/anaconda3/bin:/usr/bin:$PATH"

%post
    build_tmp=$(mktemp -d) && cd ${build_tmp}

    apt-get -y update
    apt-get -y dist-upgrade 
    DEBIAN_FRONTEND=noninteractive apt-get -yq install --no-install-recommends \
	    m4 vim-nox emacs-nox nano zip\
    	python3-pip python3-setuptools git-core inotify-tools \
	    curl git-lfs \
	    build-essential libtbb-dev
    rm -rf /var/lib/apt/cache/* 

    pip3 install --upgrade pip
    pip3 install jupyterlab
    pip3 install ipywidgets
    pip3 install gdown

    apt-get update -y 

    cd /
    rm -rf ${build_tmp}

%files
    English/ /labs

%runscript
    "$@"

%labels
    AUTHOR mozhgank
